# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-29 02:27
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('swot', '0003_auto_20180331_2319'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SwotMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', related_query_name='+', to=settings.AUTH_USER_MODEL)),
                ('member', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', related_query_name='+', to=settings.AUTH_USER_MODEL)),
                ('swot', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', related_query_name='+', to='swot.Swot')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='swotmember',
            unique_together=set([('swot', 'member')]),
        ),
    ]
