# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-29 02:58
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('swot_members', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='swotmember',
            name='added_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', related_query_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='swotmember',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', related_query_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='swotmember',
            name='swot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', related_query_name='+', to='swot.Swot'),
        ),
    ]
