# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-26 15:25
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('swot', '0003_auto_20180331_2319'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('swot_members', '0002_auto_20180429_0258'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', related_query_name='+', to=settings.AUTH_USER_MODEL)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', related_query_name='+', to=settings.AUTH_USER_MODEL)),
                ('swot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', related_query_name='+', to='swot.Swot')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='swotmember',
            unique_together=set([]),
        ),
    ]
