# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-26 18:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swot_members', '0003_auto_20180526_1525'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invite',
            name='member',
        ),
        migrations.AddField(
            model_name='invite',
            name='email',
            field=models.EmailField(default='default@mail.com', max_length=254),
            preserve_default=False,
        ),
    ]
