# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-30 03:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('swot', '0007_auto_20180330_0315'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('voteType', models.CharField(choices=[(b'up', b'UP'), (b'down', b'DOWN')], max_length=4)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='swot.SwotItem')),
            ],
        ),
    ]
