# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-01 05:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('swot', '0003_auto_20180331_2319'),
        ('swot_item_vote', '0004_auto_20180331_2343'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vote',
            old_name='item',
            new_name='swot_item',
        ),
        migrations.AddField(
            model_name='vote',
            name='swot',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', related_query_name='+', to='swot.Swot'),
        ),
    ]
