# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-12 04:24
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('swot_item', '0011_auto_20180331_2319'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('swot_item_vote', '0005_auto_20180401_0513'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together=set([('created_by', 'swot_item')]),
        ),
    ]
