# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-14 20:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swot_item', '0011_auto_20180331_2319'),
    ]

    operations = [
        migrations.AddField(
            model_name='swotitem',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
