# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-06-09 19:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swot_item', '0012_swotitem_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='swotitem',
            name='score',
            field=models.FloatField(default=0),
        ),
    ]
